baseURL = "http://localhost/"
# baseURL = "http://wa.lan/.eman/ziel/solarsystem2/public/"
# baseURL = "http://wa.lan/.eman/ziel/solarsystem2/isableFastRender/"
languageCode = "en-us"
title = "Solar System"

[markup.goldmark.renderer]
    unsafe = true
